apiVersion: v1
kind: Namespace
metadata:
  name: cdr-app

---
apiVersion: v1
kind: Service
metadata:
  name: cdr-app-svc
  namespace: cdr-app
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cdr-app
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr-app
  namespace: cdr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdr-app
  template:
    metadata:
      labels:
        app: cdr-app
    spec:
      containers:
      - name: cdr-app
        image: seyipaul/autocdr:latest
        ports:
        - containerPort: 5000
